on:
  push:
    tags:
      - 'v*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: 'rustfmt, clippy'
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: '--all -- --check'
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: '-- -D warnings'
  release:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name:
          - linux
          - windows
          - macos
        include:
          - name: linux
            os: ubuntu-latest
            asset_path: target/release/iota-mnemonic
            asset_name: iota-mnemonic-linux
          - name: windows
            os: windows-latest
            asset_path: target/release/iota-mnemonic.exe
            asset_name: iota-mnemonic-windows.exe
          - name: macos
            os: macos-latest
            asset_path: target/release/iota-mnemonic
            asset_name: iota-mnemonic-macos
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: '--release --locked'
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.asset_path }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/octet-stream
